spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_data_jpa
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#    serialization:
#      fail-on-empty-beans: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
